services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    env_file:
      - backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: /api
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - frontend/.env
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge
